version: '2.0'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
